### ISSUE TITLE
mouseenter/mouseleave do not work?

### ISSUE THREAD

**Issue by CheloXL** [dperini/nwevents#1]
Hi,

So, mouseenter/leave are only limited to IE?

It would be nice if nwevents takes cares of all that stuff automagically...

**Comment by dperini** [comment]
CheloXL,
actually mousenter/mouseleave have been included in to the latest DOM Level 3 Events specifications. NWMatcher event delegation can be used to emulate those events through mouseover/mouseout. In future maybe an add-on will be made available to hide the details of setting up mousenter/mouseleave to developers.

There is an example of how to exactly emulate the CSS ":hover" behavior for IE in the /test/ directory named "deaf-bubbling.html", it is plain easy, but will give you an idea about how to start if you want to write a small wrapper for that.

**Comment by CheloXL** [comment]
Mmm... I think I was not clear.

I'm using the event delegation. My code looks like
NW.Event.appendDelegate('#test', 'mouseenter', function(){alert("works")});

The function never gets executed (only in IE). Of course, if I change mouseenter by mouseover that works fine. The node is a div with some text inside.

**Comment by dperini** [comment]
As an example to explain try, add one of these line following the above registration:

```
NW.Event.dispatch(document.getElementById('test'), 'mouseenter');// native
NW.Event.notify(document.getElementById('test'), 'mouseenter');// manual
```

Don't be confused by seeing instances of "mouseenter/mouseleave" strings in the code, as for the example above, they are there to emulate the firing of these events using native API if (or when) the browser implements that, or being able to manually iterate through the registered handlers (emulate the event firing).

"mouseenter/mouseleave" events do not "bubble" in IE nor in DOM 3 specs so they are not good candidates for event delegation, but can actually be replaced by delegation itself and "mouseover/mouseout" for a real cross-browser solution. This is what most frameworks do actually.

Please, just give this a try in your test code:

```
NW.Event.appendDelegate('#test', 'mouseover', doSomething_over);
NW.Event.appendDelegate('#test', 'mouseout', doSomething_out);
```

then ensure ".stopPropagation()" is included in the "doSomething_xxx" handlers and setup a pure "mouseenter/mouseleave" example in IE using "attachEvent" and compare. I am not completely sure yet, just my tests but would be happy to see what I am still overlooking on this matter.

And I will also try to setup some more examples I have in the /test directory soon.

Thank you for trying NWEvents and for your suggestions, maybe I will make this transparent to users if there is enough interest but would like to first ensure I am not duplicating efforts for something that can already be done with event delegation.

**Comment by CheloXL** [comment]
mouseenter/leave can not be replaced by mouseover/out. I know how they works and that's exactly the behavior I'm looking at.

Most libraries implement enter/leave using some kind of workaround, again, because they are not part of the specs but they are very useful.

Example:
    NW.Event.appendDelegate('#test', 'mouseenter', function(pEvent){
        console.log("in:"+this.nodeName);
    });
    NW.Event.appendDelegate('#test', 'mouseleave', function(pEvent){
        console.log("out:"+this.nodeName);
    });

Try the above on this:
    <ul id="test">
        <li>One</li>
        <li>Two</li>
        <li>Three</li>
     </ul>

On Firefox, it does not works at all. On IE, you will get a "In: UL" when the mouse enters the ul (it doesn't matter if you hover the ul or the li(s) inside) and "Out: UL" when the mouse leave the ul.

mouseover/out will produce a series of "In-Out-In-Out" each time the mouse cursor leaves a LI/enters the next LI or when it leaves the UL and enters a LI or when leaves a LI and enters an UL. It is the correct behavior, but not the one I'm looking for.

I know how to fix that using mouseover/out (i have check the ancestor of the node that fired the event) but I believe that should be done by the event delegation framework.

**Comment by dperini** [comment]
These events are available and work in Firefox 10 and later releases.
They can be used in every new browsers.
