### ISSUE TITLE
NW.Event.stop not working for form submit

### ISSUE THREAD

**Issue by pdanpdan** [dperini/nwevents#2]
Hi,
In the latest version of nwevents the following example submits the form, while in 1.2.4beta/20100210 it was working ok

http://gist.github.com/322539

**Comment by dperini** [comment]
I have just tested your example, once removed the comments around the NW.Event.appendDelegate method everything seemed to work as expected.

Both NW.Event.stop() and event.preventDefault() are capable of preventing the event default action from occurring, in this case the "submit" event. Remember that "return false;" from an event handler also achieves that behavior (old DOM0).

Please retry and let me know in case I have overlooked something.

**Comment by pdanpdan** [comment]
I have updated http://gist.github.com/322539
Still the same thing, using firefox 3.6 / chome /Safari
The page is reloaded after NW.Event.stop(e)

**Comment by dperini** [comment]
ok, noticed the bug in the GitHub version. The default action on form elements cannot be prevented. Will fix that asap. Thank you for reporting.

**Comment by pdanpdan** [comment]
thank you :)

**Comment by dperini** [comment]
fixed by this commit:
http://github.com/dperini/nwevents/commit/677f3d0f5f968cf9e2578d211050ca815408e88b

**Comment by pdanpdan** [comment]
It's working now, thank you
