### ISSUE TITLE
isNative causes an error in IE8 compatibility mode and IETester

### ISSUE THREAD

**Issue by 3b0b** [dperini/nwevents#4]
'undefined' is null or not an object

I don't have a way to test in a real IE7 or lower currently, but I suspect that the user who called the error to my team's attention in the first place was using it.

The problem seems to be that window.open + '' is undefined in those environments.

**Comment by dperini** [comment]
I am skeptical into believing that "window.open" could be undefined on any browser. That could surely happen in an headless JSVM like Spidermonkey but not in a browser. Could you provide a reduced test case where NWEvents fails ?

**Comment by jdalton** [comment]
I could not reproduce ![screenshot](http://gyazo.com/bddcbbe9783126d196c1368047dabc44.png)

**Comment by 3b0b** [comment]
Certainly, I'd be happy to provide a test case.

```
<!DOCTYPE html>
<html>
    <head>
        <script type='text/javascript' src='js/nwevents-1.2.3.js'></script>
    </head>
    <body>
    </body>
</html>
```

I'm not sure what the deal is with window.open. If I try javascript:alert(window.open+'') in the address bar, I get undefined.

**Comment by dperini** [comment]
I believe you should try in Internet Explorer any version ?
That will show you the browser you are using (IETester) is not emulating correctly IE (at least not that part of IE). So I don't really get the point, or maybe I am still misunderstanding what you want to show ;-)

Also, @jdalton (above) has taken the time to download the latest IETester, tested it and confirmed that the "window.open" method is available (see picture).

**Comment by 3b0b** [comment]
Okay, I've conducted further tests with a coworker's computer and my own, in both IE8 and IETester, and it looks like my computer's IE8 is not behaving the same way as anything else, which very well may mean I have completely misdiagnosed the problem. I will post again when I get it any better figured out.

**Comment by dperini** [comment]
No problems @scriptninja !
Thank you for your testing, it may help bring up uncovered things.
Actually I could avoid using that method altogether... one day.
No doubt it was a challenge against browsers, but it works ;-)
